name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # This triggers the workflow on version tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 8.6.1

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21.x'

    - name: Install dependencies
      run: pnpm install
      working-directory: web

    - name: Build Svelte project
      run: pnpm run build
      working-directory: web

    - name: Bundle files
      run: |
        mkdir -p ./temp/mm_radio
        mkdir -p ./temp/mm_radio/build/
        cp ./{LICENSE,README.md,battery.json,fxmanifest.lua} ./temp/mm_radio
        cp -r ./{client,server,shared,locales} ./temp/mm_radio
        cp -r ./build ./temp/mm_radio/build/
        cd ./temp && zip -r ../mm_radio.zip ./mm_radio

    - name: Create Release
      uses: 'marvinpinto/action-automatic-releases@v1.2.1'
      id: auto_release
      with:
        repo_token: '${{ secrets.GITHUB_TOKEN }}'
        prerelease: false
        files: mm_radio.zip
